# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nerdctl.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nerdctl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnerdctl.proto\"3\n\rCommitRequest\x12\x13\n\x0b\x63ontainerId\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\"+\n\x0e\x43ommitResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"1\n\x14\x43ommitStreamResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"@\n\x0bPushRequest\x12\r\n\x05image\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\")\n\x0cPushResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"!\n\x12PushStreamResponse\x12\x0b\n\x03msg\x18\x01 \x01(\x0c\x32\xd4\x01\n\x0eNerdctlService\x12+\n\x06\x43ommit\x12\x0e.CommitRequest\x1a\x0f.CommitResponse\"\x00\x12\x39\n\x0c\x43ommitStream\x12\x0e.CommitRequest\x1a\x15.CommitStreamResponse\"\x00\x30\x01\x12%\n\x04Push\x12\x0c.PushRequest\x1a\r.PushResponse\"\x00\x12\x33\n\nPushStream\x12\x0c.PushRequest\x1a\x13.PushStreamResponse\"\x00\x30\x01\x42\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nerdctl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001.'
  _globals['_COMMITREQUEST']._serialized_start=17
  _globals['_COMMITREQUEST']._serialized_end=68
  _globals['_COMMITRESPONSE']._serialized_start=70
  _globals['_COMMITRESPONSE']._serialized_end=113
  _globals['_COMMITSTREAMRESPONSE']._serialized_start=115
  _globals['_COMMITSTREAMRESPONSE']._serialized_end=164
  _globals['_PUSHREQUEST']._serialized_start=166
  _globals['_PUSHREQUEST']._serialized_end=230
  _globals['_PUSHRESPONSE']._serialized_start=232
  _globals['_PUSHRESPONSE']._serialized_end=273
  _globals['_PUSHSTREAMRESPONSE']._serialized_start=275
  _globals['_PUSHSTREAMRESPONSE']._serialized_end=308
  _globals['_NERDCTLSERVICE']._serialized_start=311
  _globals['_NERDCTLSERVICE']._serialized_end=523
# @@protoc_insertion_point(module_scope)
