# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dingo_command.common.grpc_nerdctl import nerdctl_pb2 as nerdctl__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nerdctl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NerdctlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Commit = channel.unary_unary(
                '/NerdctlService/Commit',
                request_serializer=nerdctl__pb2.CommitRequest.SerializeToString,
                response_deserializer=nerdctl__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.CommitStream = channel.unary_stream(
                '/NerdctlService/CommitStream',
                request_serializer=nerdctl__pb2.CommitRequest.SerializeToString,
                response_deserializer=nerdctl__pb2.CommitStreamResponse.FromString,
                _registered_method=True)
        self.Push = channel.unary_unary(
                '/NerdctlService/Push',
                request_serializer=nerdctl__pb2.PushRequest.SerializeToString,
                response_deserializer=nerdctl__pb2.PushResponse.FromString,
                _registered_method=True)
        self.PushStream = channel.unary_stream(
                '/NerdctlService/PushStream',
                request_serializer=nerdctl__pb2.PushRequest.SerializeToString,
                response_deserializer=nerdctl__pb2.PushStreamResponse.FromString,
                _registered_method=True)


class NerdctlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Push(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NerdctlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=nerdctl__pb2.CommitRequest.FromString,
                    response_serializer=nerdctl__pb2.CommitResponse.SerializeToString,
            ),
            'CommitStream': grpc.unary_stream_rpc_method_handler(
                    servicer.CommitStream,
                    request_deserializer=nerdctl__pb2.CommitRequest.FromString,
                    response_serializer=nerdctl__pb2.CommitStreamResponse.SerializeToString,
            ),
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=nerdctl__pb2.PushRequest.FromString,
                    response_serializer=nerdctl__pb2.PushResponse.SerializeToString,
            ),
            'PushStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PushStream,
                    request_deserializer=nerdctl__pb2.PushRequest.FromString,
                    response_serializer=nerdctl__pb2.PushStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NerdctlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('NerdctlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NerdctlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NerdctlService/Commit',
            nerdctl__pb2.CommitRequest.SerializeToString,
            nerdctl__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/NerdctlService/CommitStream',
            nerdctl__pb2.CommitRequest.SerializeToString,
            nerdctl__pb2.CommitStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NerdctlService/Push',
            nerdctl__pb2.PushRequest.SerializeToString,
            nerdctl__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/NerdctlService/PushStream',
            nerdctl__pb2.PushRequest.SerializeToString,
            nerdctl__pb2.PushStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
