---
- name: Prep_kubeadm_images | Check if kubeadm binary exists at dest path
  stat:
    path: "{{ downloads.kubeadm.dest }}"
  register: kubeadm_dest_stat

- name: Install | Copy kubeadm binary from download dir
  copy:
    src: "{{ kubeadm_dest_stat.stat.exists | ternary(downloads.kubeadm.dest, local_release_dir + '/kube-' + kube_version + '/kubeadm') }}"
    dest: "{{ bin_dir }}/kubeadm"
    mode: "0755"
    remote_src: true
  tags:
    - kubeadm
  when:
    - not ('kube_control_plane' in group_names)

- name: Prep_kubeadm_images | Check if kubeadm binary exists at dest path
  stat:
    path: "{{ downloads.kubelet.dest }}"
  register: kubelet_dest_stat

- name: Install | Copy kubelet binary from download dir
  copy:
    src:  "{{ kubelet_dest_stat.stat.exists | ternary(downloads.kubelet.dest, local_release_dir + '/kube-' + kube_version + '/kubelet') }}"
    dest: "{{ bin_dir }}/kubelet"
    mode: "0755"
    remote_src: true
  tags:
    - kubelet
    - upgrade
  notify: Node | restart kubelet
